-- ============================================================
-- Payment orchestration analytics schema
-- Synthetic portfolio model: all provider names and rates are illustrative.
--
-- WARNING:
-- Running this file drops and recreates the project tables.
-- ============================================================

\set ON_ERROR_STOP on

BEGIN;

DROP TABLE IF EXISTS
    checkout_requests,
    payments,
    payment_system_monthly_pricing,
    account_risk_profiles,
    subscriptions,
    tariff_payment_conditions,
    payment_system_volume_tiers,
    tariffs,
    payment_systems,
    accounts
CASCADE;


-- ============================================================
-- 1. ACCOUNTS
-- Businesses using the orchestration platform.
-- ============================================================

CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    region VARCHAR(100) NOT NULL,
    business_segment VARCHAR(50) NOT NULL,
    company_size VARCHAR(20) NOT NULL
        CHECK (company_size IN ('small', 'medium', 'large')),
    account_status VARCHAR(20) NOT NULL
        CHECK (account_status IN ('active', 'churned')),
    closed_at TIMESTAMP,

    CHECK (
        (account_status = 'active' AND closed_at IS NULL)
        OR
        (account_status = 'churned' AND closed_at IS NOT NULL)
    ),
    CHECK (closed_at IS NULL OR closed_at > created_at)
);


-- ============================================================
-- 2. PAYMENT SYSTEMS
-- Banks, gateways, wallets and payment rails available through
-- one platform integration.
-- ============================================================

CREATE TABLE payment_systems (
    payment_system_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_system_name VARCHAR(100) UNIQUE NOT NULL,
    provider_type VARCHAR(50) NOT NULL,
    base_market_fee_rate NUMERIC(7,6) NOT NULL
        CHECK (base_market_fee_rate >= 0 AND base_market_fee_rate < 1),
    description TEXT NOT NULL,
    benefits TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);


-- ============================================================
-- 3. PAYMENT SYSTEM VOLUME TIERS
-- Wholesale provider cost depends on the total monthly traffic
-- routed through a provider across all platform customers.
-- ============================================================

CREATE TABLE payment_system_volume_tiers (
    volume_tier_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_system_id BIGINT NOT NULL,
    tier_name VARCHAR(50) NOT NULL,
    min_monthly_volume NUMERIC(18,2) NOT NULL
        CHECK (min_monthly_volume >= 0),
    max_monthly_volume NUMERIC(18,2),
    provider_cost_rate NUMERIC(7,6) NOT NULL
        CHECK (provider_cost_rate >= 0 AND provider_cost_rate < 1),

    FOREIGN KEY (payment_system_id)
        REFERENCES payment_systems(payment_system_id),

    UNIQUE (payment_system_id, tier_name),

    CHECK (
        max_monthly_volume IS NULL
        OR max_monthly_volume > min_monthly_volume
    )
);


-- ============================================================
-- 4. TARIFFS
-- Monthly SaaS subscription plans.
-- ============================================================

CREATE TABLE tariffs (
    tariff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_name VARCHAR(50) UNIQUE NOT NULL,
    monthly_price NUMERIC(14,2) NOT NULL
        CHECK (monthly_price >= 0),
    description TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);


-- ============================================================
-- 5. TARIFF PAYMENT CONDITIONS
-- Client-facing processing rate for each tariff/provider pair.
-- The actual platform margin changes with the provider volume tier.
-- ============================================================

CREATE TABLE tariff_payment_conditions (
    condition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_id BIGINT NOT NULL,
    payment_system_id BIGINT NOT NULL,
    client_fee_rate NUMERIC(7,6) NOT NULL
        CHECK (client_fee_rate >= 0 AND client_fee_rate < 1),
    discount_from_market_rate NUMERIC(7,6) NOT NULL
        CHECK (discount_from_market_rate >= 0 AND discount_from_market_rate < 1),

    FOREIGN KEY (tariff_id)
        REFERENCES tariffs(tariff_id),

    FOREIGN KEY (payment_system_id)
        REFERENCES payment_systems(payment_system_id),

    UNIQUE (tariff_id, payment_system_id)
);


-- ============================================================
-- 6. SUBSCRIPTIONS
-- Consecutive tariff periods for each customer.
-- ============================================================

CREATE TABLE subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    tariff_id BIGINT NOT NULL,
    purchased_at TIMESTAMP NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    paid_till TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL
        CHECK (status IN ('active', 'expired', 'cancelled')),

    FOREIGN KEY (account_id)
        REFERENCES accounts(account_id),

    FOREIGN KEY (tariff_id)
        REFERENCES tariffs(tariff_id),

    CHECK (purchased_at <= valid_from),
    CHECK (paid_till > valid_from)
);


-- ============================================================
-- 7. ACCOUNT RISK PROFILES
-- Risk-based pricing adds a surcharge to the client-facing rate.
-- ============================================================

CREATE TABLE account_risk_profiles (
    risk_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT UNIQUE NOT NULL,
    risk_level VARCHAR(20) NOT NULL
        CHECK (risk_level IN ('low', 'medium', 'high')),
    risk_score NUMERIC(7,4) NOT NULL
        CHECK (risk_score >= 0 AND risk_score <= 1),
    chargeback_rate NUMERIC(7,6) NOT NULL
        CHECK (chargeback_rate >= 0 AND chargeback_rate < 1),
    refund_rate NUMERIC(7,6) NOT NULL
        CHECK (refund_rate >= 0 AND refund_rate < 1),
    risk_surcharge_rate NUMERIC(7,6) NOT NULL
        CHECK (risk_surcharge_rate >= 0 AND risk_surcharge_rate < 1),
    assessed_at TIMESTAMP NOT NULL,

    FOREIGN KEY (account_id)
        REFERENCES accounts(account_id)
);


-- ============================================================
-- 8. PAYMENT SYSTEM MONTHLY PRICING
-- Records the aggregate monthly volume and wholesale tier that
-- actually applied for each provider and month.
-- ============================================================

CREATE TABLE payment_system_monthly_pricing (
    monthly_pricing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_system_id BIGINT NOT NULL,
    pricing_month DATE NOT NULL,
    monthly_volume NUMERIC(18,2) NOT NULL
        CHECK (monthly_volume >= 0),
    volume_tier_id BIGINT NOT NULL,
    provider_cost_rate NUMERIC(7,6) NOT NULL
        CHECK (provider_cost_rate >= 0 AND provider_cost_rate < 1),

    FOREIGN KEY (payment_system_id)
        REFERENCES payment_systems(payment_system_id),

    FOREIGN KEY (volume_tier_id)
        REFERENCES payment_system_volume_tiers(volume_tier_id),

    UNIQUE (payment_system_id, pricing_month)
);


-- ============================================================
-- 9. PAYMENTS
-- Each successful payment contains the merchant fee, provider cost
-- and the platform's transaction margin.
-- ============================================================

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    payment_system_id BIGINT NOT NULL,
    tariff_id BIGINT NOT NULL,
    monthly_pricing_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    amount NUMERIC(18,2) NOT NULL
        CHECK (amount >= 0),

    client_fee_rate NUMERIC(7,6) NOT NULL
        CHECK (client_fee_rate >= 0 AND client_fee_rate < 1),

    provider_cost_rate NUMERIC(7,6) NOT NULL
        CHECK (provider_cost_rate >= 0 AND provider_cost_rate < 1),

    risk_surcharge_rate NUMERIC(7,6) NOT NULL
        CHECK (risk_surcharge_rate >= 0 AND risk_surcharge_rate < 1),

    platform_margin_rate NUMERIC(7,6)
        GENERATED ALWAYS AS (client_fee_rate - provider_cost_rate) STORED,

    client_fee_amount NUMERIC(18,2) NOT NULL
        CHECK (client_fee_amount >= 0),

    payment_system_fee_amount NUMERIC(18,2) NOT NULL
        CHECK (payment_system_fee_amount >= 0),

    platform_fee_amount NUMERIC(18,2) NOT NULL
        CHECK (platform_fee_amount >= 0),

    merchant_net_amount NUMERIC(18,2) NOT NULL
        CHECK (merchant_net_amount >= 0),

    status VARCHAR(30) NOT NULL
        CHECK (status IN ('succeeded', 'failed', 'refunded', 'pending')),

    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    FOREIGN KEY (account_id)
        REFERENCES accounts(account_id),

    FOREIGN KEY (payment_system_id)
        REFERENCES payment_systems(payment_system_id),

    FOREIGN KEY (tariff_id)
        REFERENCES tariffs(tariff_id),

    FOREIGN KEY (monthly_pricing_id)
        REFERENCES payment_system_monthly_pricing(monthly_pricing_id),

    CHECK (client_fee_rate >= provider_cost_rate),
    CHECK (client_fee_amount >= payment_system_fee_amount),
    CHECK (
        ABS(
            platform_fee_amount
            - (client_fee_amount - payment_system_fee_amount)
        ) <= 0.01
    ),
    CHECK (
        (status = 'succeeded' AND is_deleted = FALSE)
        OR
        (
            client_fee_amount = 0
            AND payment_system_fee_amount = 0
            AND platform_fee_amount = 0
            AND merchant_net_amount = 0
        )
    )
);


-- ============================================================
-- 10. CHECKOUT REQUESTS
-- A customer asks to activate another provider or payment method.
-- ============================================================

CREATE TABLE checkout_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    requested_payment_system_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL
        CHECK (status IN ('new', 'in_progress', 'approved', 'rejected')),
    request_reason VARCHAR(100) NOT NULL,

    FOREIGN KEY (account_id)
        REFERENCES accounts(account_id),

    FOREIGN KEY (requested_payment_system_id)
        REFERENCES payment_systems(payment_system_id)
);


-- Helpful indexes for future analytical queries.
CREATE INDEX idx_payments_created_at
    ON payments(created_at);

CREATE INDEX idx_payments_account_id
    ON payments(account_id);

CREATE INDEX idx_payments_payment_system_id
    ON payments(payment_system_id);

CREATE INDEX idx_payments_status_deleted
    ON payments(status, is_deleted);

CREATE INDEX idx_subscriptions_account_period
    ON subscriptions(account_id, valid_from, paid_till);

CREATE INDEX idx_monthly_pricing_system_month
    ON payment_system_monthly_pricing(payment_system_id, pricing_month);


COMMIT;
