-- ===========================================
-- 1. ACCOUNTS (business customers)
-- ===========================================

CREATE TABLE accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    region VARCHAR(100) NOT NULL,
    business_segment VARCHAR(50) NOT NULL,
    company_size VARCHAR(20) NOT NULL
        CHECK (company_size IN ('small','medium','large'))
);


-- ===========================================
-- 2. PAYMENT SYSTEMS
-- Our partners: banks/payment providers
-- ===========================================

CREATE TABLE payment_systems (
    payment_system_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_system_name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    benefits TEXT,
    base_market_fee NUMERIC(5,4) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);


-- ===========================================
-- 3. TARIFFS
-- SaaS subscription plans
-- ===========================================

CREATE TABLE tariffs (
    tariff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_name VARCHAR(50) UNIQUE NOT NULL,
    monthly_price NUMERIC(12,2) NOT NULL,
    description TEXT
);


-- ===========================================
-- 4. TARIFF PAYMENT SYSTEM CONDITIONS
-- Different commission rates depending on plan and provider
-- ===========================================

CREATE TABLE tariff_payment_conditions (
    condition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tariff_id BIGINT NOT NULL,
    payment_system_id BIGINT NOT NULL,
    client_fee NUMERIC(5,4) NOT NULL,
    our_cost_fee NUMERIC(5,4) NOT NULL,
    platform_margin NUMERIC(5,4) GENERATED ALWAYS AS (client_fee - our_cost_fee) STORED,
    min_monthly_volume NUMERIC(14,2) DEFAULT 0,

    FOREIGN KEY (tariff_id) REFERENCES tariffs(tariff_id),
    FOREIGN KEY (payment_system_id) REFERENCES payment_systems(payment_system_id)
);


-- ===========================================
-- 5. SUBSCRIPTIONS
-- Customer subscription history
-- ===========================================

CREATE TABLE subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    tariff_id BIGINT NOT NULL,
    purchased_at TIMESTAMP NOT NULL,
    valid_from TIMESTAMP NOT NULL,
    paid_till TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,

    FOREIGN KEY(account_id) REFERENCES accounts(account_id),
    FOREIGN KEY(tariff_id) REFERENCES tariffs(tariff_id)
);


-- ===========================================
-- 6. PAYMENTS
-- Transactions processed through our platform
-- ===========================================

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    payment_system_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,

    amount NUMERIC(14,2) NOT NULL,

    -- cost paid to external payment provider
    payment_system_fee NUMERIC(14,2) NOT NULL,

    -- revenue earned by our platform
    platform_fee NUMERIC(14,2) NOT NULL,

    status VARCHAR(30) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,

    FOREIGN KEY(account_id) REFERENCES accounts(account_id),
    FOREIGN KEY(payment_system_id) REFERENCES payment_systems(payment_system_id)
);


-- ===========================================
-- 7. CHECKOUT REQUESTS
-- Customer requests activation of another payment provider
-- ===========================================

CREATE TABLE checkout_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    requested_payment_system_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,

    FOREIGN KEY(account_id) REFERENCES accounts(account_id),
    FOREIGN KEY(requested_payment_system_id) REFERENCES payment_systems(payment_system_id)
);
