\set ON_ERROR_STOP on

-- Run from psql:
-- \i 'C:/py/pet_project_git/saas-revenue-retention-analytics/database/02_load_data.sql'
--
-- Expected CSV directory:
-- C:/py/pet_project_git/saas-revenue-retention-analytics/data/raw/
--
-- The schema uses GENERATED BY DEFAULT AS IDENTITY, so IDs from CSV files
-- are loaded explicitly. This preserves all foreign-key relationships.

BEGIN;

TRUNCATE TABLE
    checkout_requests,
    payments,
    subscriptions,
    tariffs,
    accounts
RESTART IDENTITY CASCADE;

-- Important: psql \copy is a meta-command and must stay on one physical line.
\copy accounts (account_id, email, created_at, region, business_segment, company_size) FROM 'C:/py/pet_project_git/saas-revenue-retention-analytics/data/raw/accounts.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy tariffs (tariff_id, tariff_name, price, duration_days, is_active, created_at) FROM 'C:/py/pet_project_git/saas-revenue-retention-analytics/data/raw/tariffs.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy subscriptions (subscription_id, account_id, tariff_id, purchased_at, valid_from, paid_till, status) FROM 'C:/py/pet_project_git/saas-revenue-retention-analytics/data/raw/subscriptions.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy payments (payment_id, account_id, payment_system, created_at, amount, commission_amount, status, is_deleted) FROM 'C:/py/pet_project_git/saas-revenue-retention-analytics/data/raw/payments.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

\copy checkout_requests (request_id, account_id, requested_payment_system, created_at, status) FROM 'C:/py/pet_project_git/saas-revenue-retention-analytics/data/raw/checkout_requests.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

-- Move identity sequences after the highest imported IDs.
SELECT setval(pg_get_serial_sequence('accounts', 'account_id'), COALESCE(MAX(account_id), 1), MAX(account_id) IS NOT NULL) FROM accounts;
SELECT setval(pg_get_serial_sequence('tariffs', 'tariff_id'), COALESCE(MAX(tariff_id), 1), MAX(tariff_id) IS NOT NULL) FROM tariffs;
SELECT setval(pg_get_serial_sequence('subscriptions', 'subscription_id'), COALESCE(MAX(subscription_id), 1), MAX(subscription_id) IS NOT NULL) FROM subscriptions;
SELECT setval(pg_get_serial_sequence('payments', 'payment_id'), COALESCE(MAX(payment_id), 1), MAX(payment_id) IS NOT NULL) FROM payments;
SELECT setval(pg_get_serial_sequence('checkout_requests', 'request_id'), COALESCE(MAX(request_id), 1), MAX(request_id) IS NOT NULL) FROM checkout_requests;

COMMIT;

-- Verification: expected counts are 5000, 4, 15000, 200000 and 1000.
SELECT 'accounts' AS table_name, COUNT(*) AS row_count FROM accounts
UNION ALL
SELECT 'tariffs', COUNT(*) FROM tariffs
UNION ALL
SELECT 'subscriptions', COUNT(*) FROM subscriptions
UNION ALL
SELECT 'payments', COUNT(*) FROM payments
UNION ALL
SELECT 'checkout_requests', COUNT(*) FROM checkout_requests
ORDER BY table_name;
